### ISSUE TITLE
Compilation problem in example code (Consumer chapter, Introduction section)

### ISSUE THREAD

**Issue by lrodero** [monixio/monix.io#7]
Hi!

I was reading Monix docs (great work btw), and I think I've found a small bug in the example code. In the 'Consumer' chapter, 'Introduction' section we have:

```scala
val sumConsumer = Consumer.foldLeft[Long,Long](Coeval(0L))(_ + _)
```

But the compiler complains:
```
[error]  found   : monix.eval.Coeval[Long]
[error]  required: Long
[error]   val sumConsumer: Consumer[Long,Long] = Consumer.foldLeft[Long,Long](Coeval(0L))(_ + _
```

Replacing `Coeval(0L)` with just `0L` solves the problem:
```scala
val sumConsumer = Consumer.foldLeft[Long,Long](0L)(_ + _)
```

Hope it helps! And contragulations for your great work :)

**Comment by alexandru** [comment]
Thanks @Irodero, those docs should be ideally type-checked, but haven't found a good solution thus far. 

Will fix it.

**Comment by alexandru** [comment]
That sample is now fixed.
