### ISSUE TITLE
ScalaFiddle example in 'Javascript Event Listeners' requires adding Monix library

### ISSUE THREAD

**Issue by lrodero** [monixio/monix.io#8]
Hi,

In the _Javascript Event Listeners_ chapter there is [a link to an example in ScalaFiddle](https://beetta.scalafiddle.io/sf/0tkpBUS/3). Unfortunately when visiting the page the example does not compile because the Monix library is not included automatically. The user can solve the problem by including the library manually.

I think that if the author of the ScalaFiddle page (@alexandru I believe) adds the library then users visiting the page will have it loaded automatically (I did that in [a fork of the ScalaFiddle example](https://beetta.scalafiddle.io/sf/daUq13P/0) that seems to run ok without any user intervention).

Best,

**Comment by alexandru** [comment]
Thanks, this is sort of a problem with how they updated the RC versions of Monix in ScalaFiddle, should be more stable going forward. Will get fixed /cc @ochrons

**Comment by alexandru** [comment]
@lrodero @ochrons this is now fixed. The caching headers sent by the server are pretty aggressive so do a forced refresh if you don't see it.

**Comment by lrodero** [comment]
It works like a charm, no refresh needed.
